name: CI (sonar)

on: [push]

jobs:
  build:
    name: Sonar
    runs-on: ubuntu-latest

    steps:
      - name: Install gcovr
        run: |
          wget https://github.com/gcovr/gcovr/releases/download/3.4/gcovr-3.4-py2.py3-none-any.whl
          sudo pip install gcovr-3.4-py2.py3-none-any.whl
          rm -f gcovr-3.4-py2.py3-none-any.whl

      - name: Install Sonar wrapper
        working-directory: ${{ runner.workspace }}
        run: |
          wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip build-wrapper-linux-x86.zip

      - name: Install Sonar scanner
        working-directory: ${{ runner.workspace }}
        env:
          SONAR_SCANNER_VERSION: 3.3.0.1492
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip
          unzip sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip
          ln -s sonar-scanner-${SONAR_SCANNER_VERSION} sonar-scanner
          rm sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip
          ls -l ${{ runner.workspace }}/sonar-scanner
          ls -l ${{ runner.workspace }}/sonar-scanner/bin


      - name: Sonarcloud
        working-directory: ${{ runner.workspace }}/powsybl-iidm4cpp/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ${{ runner.workspace }}/sonar-scanner/bin/sonar-scanner -Dsonar.host.url=https://sonarcloud.io
