name: CI

on: [push]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
              name: "Ubuntu (GCC)",
              os: ubuntu-latest,
              build_type: "Debug", cxx: "g++", clang_tidy: "", sonar: "TRUE"
          }
          - {
              name: "Ubuntu (Clang)",
              os: ubuntu-latest,
              build_type: "Release", cxx: "clang++", clang_tidy: "", sonar: "FALSE"
          }
#          - {
#              name: "MacOS (Clang)",
#              os: macos-latest,
#              build_type: "Release", cxx: "clang++", clang_tidy: ""
#          }

    steps:
      - name: Install gcovr
        if: matrix.config.sonar == 'TRUE'
        run: |
          wget https://github.com/gcovr/gcovr/releases/download/3.4/gcovr-3.4-py2.py3-none-any.whl
          sudo pip install gcovr-3.4-py2.py3-none-any.whl
          rm -f gcovr-3.4-py2.py3-none-any.whl

      - name: Install Sonar wrapper
        if: matrix.config.sonar == 'TRUE'
        run: |
          wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip build-wrapper-linux-x86.zip
          echo $PWD
          ls $PWD/build-wrapper-linux-x86
          echo ${{ runner.workspace }}
